server:
  port: 8085
hm:
  db:
    database: hm-trade
  swagger:
    title: "黑马商城交易服务接口文档"
    package: com.hm.trade.controller
spring:
  rabbitmq:
    host: 172.29.191.120
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123