server:
  port: 8082
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.hm.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true #是否设置请求方式作为资源名称，默认是false